(()=>{
'use strict';
const DATA=window.PARKING_DATA;
const REF=DATA.referenceSize||{width:1536,height:1152};
const imageCache={};
const state={agent:'all',activeType:'compact',activeZone:{compact:'A',double:'A'},selectedId:null};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function normId(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}
function mapOf(type){return DATA.maps[type]}
function typeLabel(type){return mapOf(type).shortLabel}
function botName(type){return type==='compact'?'경차봇':'이열봇'}
function zonesFor(type){return [...new Set(Object.values(mapOf(type).spots).map(s=>s.zone))].sort()}
function spotsFor(type,zone){return Object.values(mapOf(type).spots).filter(s=>s.zone===zone).sort((a,b)=>a.number-b.number)}
function loadImage(type){if(imageCache[type])return imageCache[type];imageCache[type]=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=mapOf(type).image});return imageCache[type]}
function parse(q){const raw=String(q||'').trim();let type=null;if(/경차|소형|compact/i.test(raw))type='compact';if(/이열|2\s*열|double/i.test(raw))type='double';const hit=raw.toUpperCase().match(/[A-K]\s*[-_ ]?\s*\d{1,2}/);return{raw,type,id:normId(hit&&hit[0])}}
function positionInZone(type,id){const spots=mapOf(type).spots,s=spots[id];const same=Object.values(spots).filter(v=>v.zone===s.zone);const xs=same.map(v=>v.x),ys=same.map(v=>v.y);const minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);const rx=(s.x-minx)/Math.max(1,maxx-minx),ry=(s.y-miny)/Math.max(1,maxy-miny);const h=rx<.34?'왼쪽':rx>.66?'오른쪽':'가운데';const v=ry<.34?'위쪽':ry>.66?'아래쪽':'중앙';return h==='가운데'?v:(v==='중앙'?h:`${h} ${v}`)}
function nearest(type,id){const spots=mapOf(type).spots,s=spots[id];return Object.values(spots).filter(v=>v.id!==id&&v.zone===s.zone).sort((a,b)=>((a.x-s.x)**2+(a.y-s.y)**2)-((b.x-s.x)**2+(b.y-s.y)**2))[0]||null}
function description(type,id){const s=mapOf(type).spots[id];const manual=(DATA.manualDescriptions?.[type]||{})[id];if(manual)return manual;const zone=(DATA.zoneDescriptions?.[type]||{})[s.zone]||s.nearby;const pos=positionInZone(type,id),n=nearest(type,id);return `${zone}, ${s.zone}구역 ${pos}${n?`, ${n.id} 인접 자리`:''}`}
function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function marker(ctx,x,y,label,scale=1){ctx.save();ctx.lineWidth=5*scale;ctx.strokeStyle='#fff';ctx.fillStyle='rgba(229,38,59,.96)';ctx.beginPath();ctx.arc(x,y,20*scale,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.lineWidth=4*scale;ctx.strokeStyle='#ffc400';ctx.beginPath();ctx.arc(x,y,30*scale,0,Math.PI*2);ctx.stroke();ctx.font=`900 ${14*scale}px system-ui,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.fillText(label,x,y);ctx.restore()}
function labelBox(ctx,x,y,text,maxW){ctx.save();ctx.font='800 19px system-ui,sans-serif';const tw=Math.min(maxW,ctx.measureText(text).width+22),h=35;let bx=Math.min(Math.max(7,x+28),ctx.canvas.width-tw-7),by=Math.max(7,y-52);if(by+h>ctx.canvas.height-7)by=ctx.canvas.height-h-7;ctx.fillStyle='rgba(9,32,63,.9)';roundRect(ctx,bx,by,tw,h,9);ctx.fill();ctx.fillStyle='#fff';ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(text,bx+11,by+h/2);ctx.restore()}
async function drawOverall(type,id,c){const im=await loadImage(type),s=mapOf(type).spots[id],ctx=c.getContext('2d');c.width=REF.width;c.height=REF.height;ctx.drawImage(im,0,0,REF.width,REF.height);ctx.fillStyle='rgba(0,0,0,.10)';ctx.fillRect(0,0,c.width,c.height);marker(ctx,s.x,s.y,id,1.35);labelBox(ctx,s.x,s.y,`${mapOf(type).label} ${id}`,420)}
async function drawDetail(type,id,c){const im=await loadImage(type),s=mapOf(type).spots[id],ctx=c.getContext('2d');const sw=460,sh=340;let sx=Math.max(0,Math.min(REF.width-sw,s.x-sw/2)),sy=Math.max(0,Math.min(REF.height-sh,s.y-sh/2));c.width=920;c.height=680;ctx.drawImage(im,sx,sy,sw,sh,0,0,c.width,c.height);const tx=(s.x-sx)*2,ty=(s.y-sy)*2;marker(ctx,tx,ty,id,1.8);labelBox(ctx,tx,ty,`${s.zone}구역 상세 · ${id}`,520)}
function makePhotoCard(title,subtitle){const wrap=document.createElement('div');wrap.className='photo-card';wrap.innerHTML=`<div class="photo-label"><span>${esc(title)}</span><small>${esc(subtitle)}</small></div>`;const c=canvas(10,10);c.title='눌러서 크게 보기';wrap.appendChild(c);c.onclick=()=>openCanvas(c);return{wrap,c}}
function openCanvas(c){$('#modalImg').src=c.toDataURL('image/png');$('#modal').classList.add('show')}
function renderAgents(){$$('.agent').forEach(b=>{const active=b.dataset.agent===state.agent;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false')})}
function renderTypes(){$$('.type-btn').forEach(b=>{const active=b.dataset.type===state.activeType;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active?'true':'false')})}
function setAgent(agent){state.agent=agent;if(agent==='compact'||agent==='double')state.activeType=agent;state.selectedId=null;renderAgents();renderAllSelectors();setResultEmpty(agent==='all'?'통합 안내봇입니다. 경차 또는 이열부터 선택해 주세요.':`${agent==='compact'?'경차봇':'이열봇'}입니다. 구역과 번호를 선택해 주세요.`)}
function renderZones(){const type=state.activeType,zones=zonesFor(type),current=state.activeZone[type]||zones[0];$('#zones').innerHTML=zones.map(z=>`<button class="zone-btn ${z===current?'active':''}" data-zone="${z}">${z}</button>`).join('');$$('#zones .zone-btn').forEach(b=>b.onclick=()=>{state.activeZone[type]=b.dataset.zone;state.selectedId=null;renderZones();renderSpots();renderSummary()})}
function renderSpots(){const type=state.activeType,zone=state.activeZone[type],spots=spotsFor(type,zone);const picked=state.selectedId&&mapOf(type).spots[state.selectedId]?.zone===zone?`<span class="chosen">${esc(state.selectedId)} 선택됨</span>`:'';$('#spotHint').innerHTML=`<span class="zone-name">${esc(zone)}구역</span><span class="count">전체 ${spots.length}자리</span><strong>원하는 번호를 한 번 누르세요</strong>${picked}`;$('#spotList').innerHTML=spots.map(s=>`<button class="spot-btn ${s.id===state.selectedId?'active':''}" data-id="${s.id}">${s.id}</button>`).join('');$$('#spotList .spot-btn').forEach(b=>b.onclick=()=>locate(type,b.dataset.id))}
function renderSummary(message=''){const type=state.activeType,zone=state.activeZone[type],id=state.selectedId;$('#selectionSummary').innerHTML=message||`<b>현재 선택</b> · ${esc(typeLabel(type))} 지정주차 · ${esc(zone)}구역${id?` · <strong>${esc(id)}</strong>`:' · 번호를 눌러주세요'}`}
function renderAllSelectors(){renderAgents();renderTypes();renderZones();renderSpots();renderSummary()}
function setResultEmpty(message='찾을 자리를 선택해 주세요.'){$('#resultContent').hidden=true;$('#resultEmpty').hidden=false;$('#resultEmpty h2').textContent=message}
function showError(message){$('#resultEmpty').hidden=true;const out=$('#resultContent');out.hidden=false;out.innerHTML=`<div class="result-error"><b>위치를 찾지 못했습니다.</b><br>${esc(message)}</div>`}
async function locate(type,id){id=normId(id);const map=mapOf(type),s=map?.spots?.[id];if(!s){showError(`${typeLabel(type)} 지정주차 ${id||'자리번호'} 자료가 없습니다. 종류와 번호를 다시 확인해 주세요.`);return}state.activeType=type;state.activeZone[type]=s.zone;state.selectedId=id;renderAllSelectors();const loc=description(type,id),out=$('#resultContent');$('#resultEmpty').hidden=true;out.hidden=false;out.innerHTML=`<div class="answer-head"><span class="bot-badge">${esc(state.agent==='all'?'통합 안내봇':botName(type))}</span><span class="spot-title">${esc(map.label)} ${esc(id)}</span></div><div class="tags"><span class="tag">${esc(s.zone)}구역</span><span class="tag">${esc(s.nearby)}</span></div><p class="answer-text"><strong>${esc(map.shortLabel)} ${esc(id)}</strong>은(는) 도면 기준으로 <strong>${esc(loc)}</strong>에 있습니다.<br>전체 배치도와 ${esc(s.zone)}구역 상세도를 함께 확인하세요.</p><div class="legend"><span><i class="dot red"></i>검색한 자리</span><span><i class="dot yellow"></i>강조 표시</span></div>`;const grid=document.createElement('div');grid.className='image-grid';const overall=makePhotoCard('① 전체 배치도','단지 안의 큰 위치');const detail=makePhotoCard(`② ${s.zone}구역 상세도`,'인쇄 번호와 주변 자리');grid.append(overall.wrap,detail.wrap);out.appendChild(grid);await Promise.all([drawOverall(type,id,overall.c),drawDetail(type,id,detail.c)]);out.scrollIntoView({behavior:'smooth',block:'start'})}
function resolveType(parsed){if(parsed.type)return parsed.type;if(state.agent==='compact'||state.agent==='double')return state.agent;const candidates=['compact','double'].filter(t=>mapOf(t).spots[parsed.id]);if(candidates.length===1)return candidates[0];return state.activeType}
function search(text){const q=String(text??$('#query').value).trim();if(!q)return;$('#query').value='';const p=parse(q);if(!p.id){showError('예: 경차 G-7 또는 이열 F-3처럼 입력해 주세요.');return}const type=resolveType(p);if(!mapOf(type).spots[p.id]&&state.agent==='all'&&!p.type){const other=type==='compact'?'double':'compact';if(mapOf(other).spots[p.id])return locate(other,p.id)}locate(type,p.id)}
function init(){$$('.agent').forEach(b=>b.onclick=()=>setAgent(b.dataset.agent));$$('.type-btn').forEach(b=>b.onclick=()=>{const type=b.dataset.type;state.activeType=type;if(state.agent!=='all')state.agent=type;state.selectedId=null;renderAllSelectors();setResultEmpty(`${typeLabel(type)} 지정주차를 선택했습니다. 구역과 번호를 눌러주세요.`)});$('#send').onclick=()=>search();$('#query').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$$('.sample-btn').forEach(b=>b.onclick=()=>search(b.dataset.q));$('#modalClose').onclick=()=>$('#modal').classList.remove('show');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('show')};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('show')});renderAllSelectors()}
init();
})();
